### ISSUE TITLE
RE: Removed from plugin hub 

### ISSUE THREAD

**Issue by EkiraErnest** [neilrush/Camera-Keys#10]
Seems its been removed with a bunch of other plugins due to being out of date? 
 — Today at 6:06 PM
Some hub plugins failed to build against the latest RuneLite version, this means that they're not available until the owner updates them.

**Comment by neilrush** [comment]
I have the changes ready to submit.
I did not realize the update was going out so soon. They only just notified people of the changes yesterday. :/

**Comment by neilrush** [comment]
The changes are in the pipeline. 
Thanks for letting me know that something was wrong :)
