### ISSUE TITLE
Zoom always max

### ISSUE THREAD

**Issue by Damien-Sullivan** [neilrush/Camera-Keys#13]
For me, the zoom level does not do anything and no matter what number I set it zooms all the way out. 

I've tried reinstalling and resetting default settings with no luck

**Comment by neilrush** [comment]
I investigated this over the weekend. I couldn't replicate what you experienced. 

The zoom level ranges from -272 (zoomed all the way out) to 1300 (zoomed all the way in).
Try a value of 1300 and see if it zooms in. 

Let me know if you still have an issue.

**Comment by Damien-Sullivan** [comment]
Oh there's my issue. I was thinking it was 0-10 so it wasn't moving much. Hope I didn't waste too much time sorry, thank you!

**Comment by neilrush** [comment]
Good to hear. Yeah the numbers are kinda odd because they are the exact numbers used by the game back end.
