### ISSUE TITLE
Feature Request - Resetting the yaw

### ISSUE THREAD

**Issue by archubbuck** [neilrush/Camera-Keys#14]
Is this something you'd be able to add?

**Comment by neilrush** [comment]
I think this would be a great feature, but Jagex does not allow presets for camera yaw/pitch/position. The only allowed way to change the camera position with a plugin is the zoom or the compass, as per the [Plugin Guildlines](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#not-currently-being-considered).
