### ISSUE TITLE
Plugin throws NPEs on first install

### ISSUE THREAD

**Issue by equirs** [neilrush/Camera-Keys#3]
The default keybinds for the compass keys are null, and are not safely checked, which also breaks the key remapping plugin, so no keyboard input from that point on registers.

**Comment by neilrush** [comment]
Someone else in the Runelite discord had this issue but I was not able to duplicate it. I suspect it may be java version specific. 

Could you let me know what distro of java you are running? (Adoptium, Oracle etc.)
Also, if you have a log with the NPE stacktrace.

**Comment by equirs** [comment]
You're probably not able to repro it because as soon as you set all the keybinds, it returns a non-null value, and your config is persisted beyond plugin reinstalls. Unfortunately, I missed the chance to copy the stacktrace but it should be simple enough to search for any usages of your config's keybinds and check whether they're null first. Or you could just change your config's default return values to the same values that the `NOT_SET` static keybind defines. That would probably fix the issue. I don't think it's related to Java distro, but I'm using OpenJDK 11

**Comment by neilrush** [comment]
I did delete the config while testing 🤔, but I think you are right. I have set the default keybind to `ModifierlessKeybind(KeyEvent.VK_UNDEFINED)` which matches what is in the [keybind class](https://github.com/runelite/runelite/blob/e3840ca1fadef104ca473fb26029432b3063e855/runelite-client/src/main/java/net/runelite/client/config/Keybind.java) for `NOT_SET`. Hopefully that fixes the issue.
